# Generated by Django 4.0.1 on 2022-01-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artysta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('rok_smierci', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eksponat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('rzezba', 'Rzezba'), ('obraz', 'Obraz'), ('inny', 'Inny')], max_length=10)),
                ('stan', models.CharField(choices=[('wypozyczony', 'Wypozyczony'), ('w ekspozycji', 'W Ekspozycji'), ('w magazynie', 'W Magazynie')], max_length=20)),
                ('id_wypozyczenia', models.PositiveIntegerField(blank=True, null=True)),
                ('id_ekspozycji', models.PositiveIntegerField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muzeum.artysta')),
            ],
        ),
        migrations.CreateModel(
            name='Instytucja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('miasto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_eksponatu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='muzeum.eksponat')),
                ('id_instytucji', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='muzeum.instytucja')),
            ],
        ),
        migrations.CreateModel(
            name='Ekspozycja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria', models.CharField(max_length=200)),
                ('sala', models.CharField(max_length=200)),
                ('id_eksponatu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='muzeum.eksponat')),
            ],
        ),
    ]
