# Generated by Django 4.0.1 on 2022-01-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum', '0002_alter_artysta_options_alter_eksponat_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ekspozycja',
            old_name='id_eksponatu',
            new_name='eksponat',
        ),
        migrations.RenameField(
            model_name='wypozyczenie',
            old_name='id_eksponatu',
            new_name='eksponat',
        ),
        migrations.RenameField(
            model_name='wypozyczenie',
            old_name='id_instytucji',
            new_name='instytucja',
        ),
    ]
