# Generated by Django 4.0.1 on 2022-01-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum', '0003_rename_id_eksponatu_ekspozycja_eksponat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksponat',
            name='wypozyczalny',
            field=models.BooleanField(default=True),
        ),
    ]
