# Generated by Django 4.0.1 on 2022-01-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum', '0004_eksponat_wypozyczalny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eksponat',
            name='id_ekspozycji',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eksponat',
            name='id_wypozyczenia',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
