# Generated by Django 4.0.1 on 2022-01-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum', '0005_alter_eksponat_id_ekspozycji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eksponat',
            name='szerokosc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eksponat',
            name='waga',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eksponat',
            name='wysokosc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
