# Generated by Django 4.0.1 on 2022-01-21 23:21

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum', '0006_eksponat_szerokosc_eksponat_waga_eksponat_wysokosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekspozycja',
            name='koniec',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 23, 21, 2, 15311, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ekspozycja',
            name='poczatek',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
