# Generated by Django 4.0.1 on 2022-01-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzeum', '0009_alter_instytucja_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eksponat',
            name='tytul',
            field=models.CharField(max_length=200, verbose_name='tytul eksponatu'),
        ),
    ]
